apiVersion: v1
kind: Service
metadata:
  name: finance-tracker-frontend
  namespace: finance-tracker
spec:
  selector:
    app: finance-tracker-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
