apiVersion: v1
kind: Service
metadata:
  name: finance-tracker-backend
  namespace: finance-tracker
spec:
  selector:
    app: finance-tracker-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
