apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-tracker-backend
  namespace: finance-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-tracker-backend
  template:
    metadata:
      labels:
        app: finance-tracker-backend
    spec:
      containers:
      - name: backend
        image: <aws_account_id>.dkr.ecr.eu-west-2.amazonaws.com/finance-tracker-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: finance-tracker-secrets
              key: DATABASE_URL
